name: phonenumbers
description: Phone number validation and input widget written in pure dart without any native dependency
version: 1.1.0
homepage: https://github.com/fonibo/phonenumbers

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  phonenumbers_core:
    git:
      url: git@github.com:thisisyusub/phonenumbers.git
      path: core
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
